### ISSUE TITLE
Large Hotel Lobby uses wrong occupancy schedule

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1020]
It is using the general hotel occupancy schedule, it should be using the lobby specific occupancy schedule. I need to update the spreadsheet to reflect this and then re-generate the schedules. Spot checking other areas this is fine, may have just been isolated error on the spreadsheet. This wasn't evident prior to 1.3.0 because it didn't impact the old templates, only people using on demand generator.

@macumber I don't see any reason to rush and get this in 1.3.3. So my plan is to accept your pull request for other template changes and then fix this issue for 1.3.4. Ti keep from updating to much I thought maybe we can just update the templates once per iteration?

The fix is two parts, first update standards spreadsheet. Then remake template and copy into core OpenStudio.

**Comment by asparke2** [comment]
@DavidGoldwasser can you confirm that this is fixed and close?

**Comment by DavidGoldwasser** [comment]
@DavidGoldwasser confirm this and add to bug as standards repo.

**Comment by DavidGoldwasser** [comment]
@asparke2 This is still an issue. The schedule for LargeHotel with Load Library still uses the same occupancy schedule everywhere.

SpaceTypeAndConstructionSet Wizard and Prototype have unique schedules for Guestroom vs. everywhere else, but still look very similar to Guestroom setting except fro late night peak. Screenshots below are from prototype measure in 2.3.0. I looked for issue in OpenStudio standards but couldn't find it.

<img width="1680" alt="screen shot 2017-11-28 at 3 33 40 pm" src="https://user-images.githubusercontent.com/4857055/33348029-0c3eeeca-d452-11e7-9142-1b54271675ca.png">

Here is Typical building occupancy schedule
<img width="1680" alt="screen shot 2017-11-28 at 3 33 09 pm" src="https://user-images.githubusercontent.com/4857055/33348046-17007d9c-d452-11e7-9b1d-58568ccd528f.png">

Here is schedule use for Guestroom
<img width="1680" alt="screen shot 2017-11-28 at 3 33 06 pm" src="https://user-images.githubusercontent.com/4857055/33348105-41983662-d452-11e7-9e5a-197748f9e4f3.png">

**Comment by jmarrec** [comment]
This is an openstudio-standards things anyways, so I will close this but I will check if fixed and if need to open an issue on os-standards first.

**Comment by jmarrec** [comment]
Moving to https://github.com/NREL/openstudio-standards/issues/600
