### ISSUE TITLE
OS:WindowMaterial:GlazingGroup:Thermochromic is wrong

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1329]
Should have an extensible list of pairs of Optical Data Temperature (double) and Window Material Glazing Name (drop down list)

**Comment by jmarrec** [comment]
Should be addressed in #1697

**Comment by evanweaver** [comment]
@macumber can you verify that this was fixed by #1697? Thanks.

**Comment by asparke2** [comment]
Here's what I see in 2.4.0, not sure if I'm missing something.

![image](https://user-images.githubusercontent.com/2009290/34890495-5e72be8c-f78f-11e7-90b1-429c520dfb21.png)

**Comment by macumber** [comment]
#1697 is another issue so it doesn't fix anything, I think Julien just meant it is a duplicate issue?  This object is not showing up correctly in the GUI, it's also weird that the default names are "80", "80 1".  Basic weirdness going on

**Comment by jmarrec** [comment]
I think it did mean it was a duplicate (rewrapping is actually what’s needed probably).

——
Sent from a mobile device, please excuse the brevity.
Julien Marrec, EBCP, BPI MFBA
Owner


Direct: +33 6 95 14 42 13
Website: www.effibem.com

LinkedIn (en) | (fr)

**Comment by jmarrec** [comment]
Yeah duplicate of #1697  which involves properly wrapping the object, I suggest closing this one for clarity.

#1697 is labeled as an Enhancement Request, which is partly true, but I'd also consider it a bug because we have an unusable thing in the OS App currently...

**Comment by jmarrec** [comment]
Rendered moot by #3233. Can you close please @macumber?
