### ISSUE TITLE
Odd 'Rated Pump Head' display unit for LowTemperatureRadiant:ConstantFlow

### ISSUE THREAD

**Issue by eringold** [NREL/OpenStudio#2343]
OS v1.12.2:
![ratedpumphead](https://cloud.githubusercontent.com/assets/10799524/18012648/b6f5295a-6b77-11e6-9808-0d217c2e984a.png)

The SI unit preference displays correctly as Pa. 

FYI @macumber

**Comment by macumber** [comment]
I'll have to ask @evanweaver if it is easy to override these units (maybe a setting in the IDD?)

**Comment by evanweaver** [comment]
Potentially setting the desired IP unit in the IDD would work. Otherwise, getting into the units code to do an override would be required and this would then be used in every auto-generated field using PA.

**Comment by jmarrec** [comment]
This is fixed in 2.6.0:

![image](https://user-images.githubusercontent.com/5479063/42690173-986bd5a8-86a3-11e8-9538-8a4d287d3c37.png)


Please confirm and close @eringold

**Comment by eringold** [comment]
@jmarrec I still see it in Windows v2.6.0:

![image](https://user-images.githubusercontent.com/10799524/42696254-e2881e00-8674-11e8-91a1-8e94fd5613da.png)

**Comment by jmarrec** [comment]
Sorry I didn’t read the title, I checked pump constant/variable flow.
So this object is missing an \ip-units flag, easy fix
