### ISSUE TITLE
OS APP 2.0.1 Standard Building and Space TypeType isn't populating from openstudio-standards

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2459]
It also doesn't let you type in custom string.

cc: @asparke2

**Comment by macumber** [comment]
@DavidGoldwasser i think this is fixed, can you test in newest installer?

**Comment by DavidGoldwasser** [comment]
I'll check this in next installer. It is still mostly broken in the pre 2.0.4 installer from a few days ago.

**Comment by DavidGoldwasser** [comment]
@macumber still an issue with last nights 2.0.4 installer. Building type populates fine, it is the space types that don't also still can't type in text.

![screen shot 2017-03-07 at 12 11 22 pm](https://cloud.githubusercontent.com/assets/4857055/23673384/5da8d950-032f-11e7-9e4c-f0544f8e34f4.png)

**Comment by DavidGoldwasser** [comment]
@macumber for Constructions, Standard, Intended Surface Type and Standards Construction Type work (note: CEC is only standards option, which may be fine, but user can type)

All other fields are locked, but oddly on new model this isn't an issue, not sure what is happening.

![screen shot 2017-03-07 at 12 14 01 pm](https://cloud.githubusercontent.com/assets/4857055/23673578/0b138356-0330-11e7-9819-4462f17b668d.png)

**Comment by DavidGoldwasser** [comment]
Even on new model the composite fields in materials are still locked out

![screen shot 2017-03-07 at 12 19 27 pm](https://cloud.githubusercontent.com/assets/4857055/23673684/6b22e728-0330-11e7-8166-d83877c779f9.png)

**Comment by macumber** [comment]
It sounds like some fields are working but others are not?  Can we get a list of the fields that are not working?  Also, it is probably time to update the JSON in OS App?

@asparke2 FYI

**Comment by DavidGoldwasser** [comment]
@macumber and @asparke2 I hit this again creating test model for ParkingGarage, I have a work around,but if not for June, then for September release it would be nice to fix this.

I did find out that the issue in Space Type tab where you see space type's for wrong building type seems to be an update issue. If I change from Hospital to Hotel, I sill still see Hospital space types. If I leave the tab and come back, or make a new space type, the space types will update.

**Comment by jmarrec** [comment]
This should have been addressed, some works was done circa 270 (eg https://github.com/NREL/OpenStudio/commit/d2acab4052891f617aca0f10fd85991f15c4a23a)

Should be reopened on OSApp if not.
