### ISSUE TITLE
PAT duplicate measure names don't increment

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#2570]
When you duplicate a measure Foo in PAT 2.1.0, you get "Foo 2". If you then duplicate "Foo 2", you get "Foo 2 2" instead of "Foo 3". It does work correctly if you duplicate measure "Foo" twice.

@asparke2

**Comment by shorowit** [comment]
I should clarify that this is in algorithmic mode.

**Comment by DavidGoldwasser** [comment]
Behavior is same in manual model

**Comment by rHorsey** [comment]
Confirmed fixed in 2.2.0

**Comment by shorowit** [comment]
This is not fixed. Screenshot from PAT 2.2.1:
![image](https://user-images.githubusercontent.com/5861765/29458059-7f20466e-83da-11e7-81c4-13ee946c9bf0.png)

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#18
