### ISSUE TITLE
PAT RUNS FOR EVER 

### ISSUE THREAD

**Issue by tabuimara** [NREL/OpenStudio#2701]
SINCE I UPDATED OPEN-STUDIO to 2.2.0, I am not able to perform any parametric analysis , the process starts and keeps in progress forever . I thought might be an issue with one of the weather files , so i tested them one at a time , nothing changes !

**Comment by DavidGoldwasser** [comment]
@tabuimara What is the status in the green bar? Does it show "Analysis Started" or is it something else? Also have you seen this on multiple PAT projects and does it still happen after a fresh restart of your computer.

**Comment by tabuimara** [comment]
Hi
It does start and says analysis starts

Tareq Isamil Abuimara, MSc, MRAIC
Cell: (613)898-1406
PhD Student/ TA/RA
Faculty of Engineering and Design

**Comment by DavidGoldwasser** [comment]
Assuming you are running on local machine, what do you see at http://localhost:8080/

Do you see an analysis, and does that analysis seem to have any datapoints, and in the GUI on the Run tab under the row for each Datapoint is the status "Started" for at least some of the datapoints?

**Comment by tabuimara** [comment]
Hi David
Sorry for my late reply.
Yes I am running on local server and the analysis starts, the data points are created and the stutus is started.
What happens is different each an every time , it either starts with no end or fails right away .
Thanks

Tareq Isamil Abuimara, MSc, MRAIC
Cell: (613)898-1406
PhD Student/ TA/RA
Faculty of Engineering and Design

**Comment by DavidGoldwasser** [comment]
Sorry, I have a few more questions. What operating system are you on, and if you restart your machine, make a fresh PAT project (something really basic without all of the same measures) does it run? If it is unique to a specific project might have you send it to us at OpenStudio@nrel.gov.

**Comment by tabuimara** [comment]
Thanks for your response
I am using Windows 64bit
I did the following and did not work :

  *   Restarted my computer several time
  *   Uninstall OS and Reinstall multiple times
  *   Changed the set of measures
I am now back to version 2.1.0 to see if the problem is with OS or my local computer , will get back to you as soon as I am done.
Thanks

Tareq Isamil Abuimara, MSc, MRAIC
Cell: (613)898-1406
PhD Student/ TA/RA
Faculty of Engineering and Design

**Comment by DavidGoldwasser** [comment]
@tabulimara. I got your email, and saw that now, you are not getting it running forever, but the datapoints are failing. The behavior appears to be related to issue #2557 which is closed and should be fixed, so I'm not sure why you are seeing it. If you are using a PAT project that pre-dates the fix, then I can see this happening. 

I'm seeing this error
```
	bin/delayed_job:6:in `<main>'
[11:52:14.211511 ERROR] C:/openstudio-2.2.0/pat/OpenStudio-server/gems/gems/openstudio-workflow-1.3.1/lib/openstudio/workflow/util/measure.rb failed with message Error assigning argument in measure C:/openstudio-2.2.0/pat/OpenStudio-server/gems/gems/openstudio-workflow-1.3.1/lib/openstudio/workflow/util/measure.rb. Failed with Could not set argument 'construction' to value '', C:/openstudio-2.2.0/pat/OpenStudio-server/gems/gems/openstudio-workflow-1.3.1/lib/openstudio/workflow/util/measure.rb:186:in `apply_arguments_2'
```
That appears to come from the Add Overhang by Projection Factor measure

```
    #make an argument for construction
    construction = OpenStudio::Ruleset::OSArgument::makeChoiceArgument("construction", construction_handles, construction_display_names,false)
    construction.setDisplayName("Optionally Choose a Construction for the Overhangs.")
    args << construction
```

I just got this information out of the run.log by unizpping one of the data_point.zip files in the localResults folder.  I haven't had a chance to run the project here, but What I would try is to remove the measure from the workflow. Save PAT, then re-add the measure back, and see if this goes away. You can also just pick an opaque construction for the shading surfaces to see if that resolves the issue. You may hit similar issue in other measures for example the optional plenum zones. If I get a chance I'll try this approach on your project, but if you have a chance you may want to try it first.

**Comment by tabuimara** [comment]
Hi David
Hope you are doing well
I still have the same issue withPAT
DATAPOINT FAILURE
I have sent you the project earlier on the other email, any thoughts ?
Thanks


Tareq I. A. Abuimara
Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by asparke2** [comment]
@chrisbalbach reported this issue, demonstrated it, and I have a PAT project that replicates the issue (on Windows at least).  Basically what's happening is that one of the design alternatives is getting re-run over and over again and never completes, even though the simulation finishes and everything.

**Comment by asparke2** [comment]
We believe that this issue is the result of having some reserved characters (periods, dollar signs) in the measure option and/or design alternative names.  This hypothesis is being tested and if it is true we will add GUI logic into PAT to warn users ahead of time.  The better long term solution to allow these characters in the names may be pursued in the future.

**Comment by rHorsey** [comment]
This issue was moved to NREL/OpenStudio-server#252
