### ISSUE TITLE
PAT is not building correctly as part of OS Package

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2984]
make pat and/or make package appears to complete normally w/ PAT SHA fafec93a277de332dda7913210a9851b712cf645.  The binary is created and packaged, but when launched the App window opens and hangs - no project dialog, diagnostic messages, or anything available.  Kat suspects the new Electron dependency may be causing problems.  Kyle and I have been unable to resolve this.

Build log:

[Build_log_from_latest_SHA.txt](https://github.com/NREL/OpenStudio/files/1682479/Build_log_from_latest_SHA.txt)

**Comment by evanweaver** [comment]
This issue was caused with the following commit:
https://github.com/NREL/OpenStudio-PAT/commit/1ba1107d638db67e3f1d1bf4b300230528d10849

**Comment by kflemin** [comment]
This should be fixed 2addb0f8d4882e7ea60c8872ee183ecb23fb49a2.

**Comment by ljbrackney** [comment]
Symptoms have changed, but PAT is still not functional within packages. 

https://github.com/NREL/OpenStudio-PAT/issues/61

**Comment by ljbrackney** [comment]
Resolved
